echo " "
echo "Help for 'stim' function."
echo "  stim [args] will wait for camera frames, and send triggers to a stimulation device, synchronizing camera frames and stimulation."
echo " "
echo "  USAGE: "
echo " "
echo "    stim [noff] [nimtr] [ntr] [duration] [frequency] [pulse_width] [imaging_framerate] [input_pin (optional; default=11)] [trigger_pin (optional; default=13)]"
echo " "
echo "    noff = number of frames before stimulus start"
echo "    nimtr = number of frames per stimulation trial"
echo "    ntr = number of repetitions of stimulus"
echo " "
echo "    duration = duration of the stimulus in (s)"
echo "    frequency = frequency of the stimulus (Hz)"
echo "    pulse_width = width of stimulus pulse (ms)"
echo "      NOTE: duration, frequency, and pulse_width will be checked to make sure values are valid."
echo " "
echo "    ex 1: stim 100 200 10 4 20 10 5         - this option keeps the default trigger pins"
echo "    ex 2: stim 100 200 10 4 20 10 5 13 15   - this option changes the default trigger pins"
echo " "
echo " "
echo "  If error with pin being in use occurs, raspi must be restarted."
echo "    restart by typing in terminal: 'reboot'"
echo "  To cleanly terminate stim program, hold 'c' and 'z' key down at same time."
echo " "